### ISSUE TITLE
Use local registry as a pull through cache for db

### ISSUE THREAD

**Issue by wkoot** [aquasecurity/trivy-db#449]
Separate ticket as requested in https://github.com/aquasecurity/trivy-db/issues/441#issuecomment-2411744048 - additional feature to #441.

Just like it would allow the Gitlab proxy, shouldn't this work with any proxy (and therefore reduce load)?
Therefore, setting up a local [Registry as a pull through cache](https://docs.docker.com/docker-hub/mirror/) should be possible.
If so, this is worth explicitly documenting on https://aquasecurity.github.io/trivy/v0.56/docs/configuration/db/

**Comment by knqyf263** [comment]
I ran the following commands, but it didn't work.

```
$ docker run -d -p 5000:5000 --restart=always --name registry -e REGISTRY_PROXY_REMOTEURL=https://ghcr.io registry:2
$ docker pull localhost:5000/aquasecurity/trivy-db:2
2: Pulling from aquasecurity/trivy-db
unsupported media type application/vnd.aquasec.trivy.config.v1+json
$ oras pull localhost:5000/aquasecurity/trivy-db:2
Error response from registry: recognizable error message not found: GET "http://localhost:5000/v2/aquasecurity/trivy-db/manifests/2": response status code 403: Forbidden
$ crane pull --insecure localhost:5000/aquasecurity/trivy-db:2 foo.tar
2024/10/15 11:19:15 retrying net/http: TLS handshake timeout
2024/10/15 11:19:25 retrying net/http: TLS handshake timeout
2024/10/15 11:19:36 retrying net/http: TLS handshake timeout
Error: Get "https://localhost:5000/v2/": net/http: TLS handshake timeout; GET http://localhost:5000/v2/: unexpected status code 403 Forbidden
```

In the case of Docker, it seems to be going to GHCR for queries, but the others are failing with 403. While Docker has [a configuration for mirrors](https://docs.docker.com/docker-hub/mirror/#configure-the-docker-daemon), we have no idea about that protocol. It would be appreciated if someone could share the knowledge.

**Comment by wkoot** [comment]
What happens when you pull `http://localhost:(etc)`  ?

**Comment by wkoot** [comment]
The following commands are working with a local registry on https:
```
docker exec -i "${CONTAINER_NAME}" trivy image --download-db-only --db-repository local-registry/aquasec/trivy-db
docker exec -i "${CONTAINER_NAME}" trivy image --download-java-db-only --java-db-repository local-registry/aquasec/trivy-java-db
```
Documentation can be improved however, see also https://github.com/aquasecurity/trivy/discussions/7794

**Comment by knqyf263** [comment]
@wkoot Did you configure the local registry as a pull-through cache?

**Comment by wkoot** [comment]
Yes, using `registry:2.8.3`. But I'm not running a custom `REGISTRY_PROXY_REMOTEURL`, just the default docker hub.
Aside from mapping port 5000, port 5001 is also mapped to provide a https interface for pulling.
I don't need to provide port number in the docker run; so no `local-registry:5000` but just `local-registry`.

**Comment by knqyf263** [comment]
>To configure a Registry to run as a pull through cache, the addition of a proxy section is required to the config file.

According to [the document](https://docs.docker.com/docker-hub/mirror/), the proxy setting seems to be required. Could you share the commands you ran?

**Comment by wkoot** [comment]
I'm using a config file mounted to `/etc/docker/registry/config.yml` in the container:
```
---
version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: 0.0.0.0:5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
proxy:
  remoteurl: https://registry-1.docker.io
  username: [[[docker-username]]]
  password: [[[docker-api-token]]]
delete:
  enabled: true
maintenance:
  uploadpurging:
    enabled: true
    age: 24h
    interval: 1h
    dryrun: false
  readonly:
    enabled: false
```
