### ISSUE TITLE
Missing CVE-2016-2781 and CVE-2022-3219 vulnerabilities in eclipse-temurin:17-jre-alpine image

### ISSUE THREAD

**Issue by Universe1609** [aquasecurity/trivy-db#500]
Hello everyone,

I'm not sure if this is an error or if I'm not scanning correctly. Here's some context:

I'm scanning the image eclipse-temurin:17-jre-alpine with Trivy and another scanning tool, "GRY". Trivy does not detect any vulnerabilities, but GRY reports the following:

CVE-2016-2781-coreutils
CVE-2016-2781-coreutils-env
CVE-2016-2781-coreutils-fmt
CVE-2016-2781-coreutils-sha512sum
CVE-2022-3219-gnupg
CVE-2022-3219-gnupg-gpgconf
CVE-2022-3219-gnupg-keyboxd
CVE-2022-3219-gnupg-utils
CVE-2022-3219-gnupg-wks-client
CVE-2022-3219-gpg
CVE-2022-3219-gpg-agent
CVE-2022-3219-gpg-wks-server
CVE-2022-3219-gpgsm
CVE-2022-3219-gpgv

These vulnerabilities are reported with Medium and Low severity.

For additional context, here is the GitHub Actions step I am using for the scan:

```
- name: Run Trivy vulnerability scanner
      if: always()
      uses: aquasecurity/trivy-action@0.29.0
      id: scan-trivy
      with:
        image-ref: 'mytest/eclipsetemurin:17-jre'
        format: 'sarif'
        severity: 'LOW,MEDIUM,HIGH,CRITICAL'
        output: 'trivy-results.sarif'
        version: latest
```
And the Dockerfile:
```
FROM eclipse-temurin:17-jre-alpine

RUN rm -rf /var/cache/apk/*

WORKDIR /opt

HEALTHCHECK NONE

CMD ["sleep", "infinity"]
```
And the packages affected, which are in the container:

![Image](https://github.com/user-attachments/assets/f912dd79-6ec8-4c51-a0dd-e44d07d87805)

Why does GRY report these vulnerabilities while Trivy does not? 
Is there a known difference in how these tools map packages and vulnerabilities?
